name: Update Kalender

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # alle 6 Stunden

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests ics pytz

      - name: Run script
        run: python script.py
        
      - name: Commit kalender.ics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/kalender.ics
          git commit -m "Update kalender" || echo "No changes"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/m-haaf/tsv-algesdorf-kalender-spiele.git
          git push origin main
